### ISSUE TITLE
Display first slide divider on top

### ISSUE THREAD

**Issue by harishsn** [IbrahimSulai/react-native-circular-multiple-slider#1]
Trying to customise according to my need. first slide divider is being hidden by the last linear gradient. how to get first slide divider on top just like all other dividers ? 
![IMG_3024](https://user-images.githubusercontent.com/8030129/69613445-966ac400-1057-11ea-8609-b51548ab9f0d.PNG)

**Comment by IbrahimSulai** [comment]
Hi Harish,
Whether you are planning to go ahead with "slideDividerType" as "Circle" or any other icon you are planning to use.

**Comment by harishsn** [comment]
I am planning to go ahead with Circle

**Comment by IbrahimSulai** [comment]
Then we need to fix fit. Give me some time. Will fix this issue.

**Comment by IbrahimSulai** [comment]
![Screenshot 2019-11-27 at 2 49 55 PM](https://user-images.githubusercontent.com/33604125/69710342-3cd0cb00-1125-11ea-9059-034f824cff4a.png)


For avoiding this issue only, I have used the line indicator at the start of the arc.

**Comment by harishsn** [comment]
Thanks, Since you asked, will it work of i use icon instead of Circle as slide divider ?

**Comment by IbrahimSulai** [comment]
Since the start point has the overlay issue. the icon will also have same issue. Please check and confirm also from ur end.

**Comment by harishsn** [comment]
Yes, even icon has same issue

**Comment by harishsn** [comment]
@IbrahimSulai  Any update ?

**Comment by IbrahimSulai** [comment]
@harishsn - sorry for the delay.

I have held up on other tasks this week. Will solve this by this weekend without fail. Thanks in advance for understanding.

**Comment by harishsn** [comment]
@IbrahimSulai No problem, Nice work on this repo btw.

**Comment by IbrahimSulai** [comment]
@harishsn - Solved the issue as you needed for your requirement in the branch [feature-divider-separation](https://github.com/IbrahimSulai/react-native-circular-multiple-slider/tree/feature-divider-separation).

Please note this branch is dedicatedly created for you. Only for your reference and usage.

Please let me know if you need any other clarification/help required.

Please close this issue if your problem solved.

**Comment by harishsn** [comment]
![issue](https://user-images.githubusercontent.com/8030129/70424835-0cc6e780-1a96-11ea-8077-adf79aacba87.gif)

Facing an issue with minimumStopValue.

**Comment by IbrahimSulai** [comment]
@harishsn - Will look into this and let you know the solution.

**Comment by IbrahimSulai** [comment]
I did quick round of look into this issue.

"minimumStopValue" is mandatory if the slider value is more than 2.

In your case, it is 4 slider, so it will be having in-between sliders while crossing the limit. so it is not able to track and draw the slider.

It will work perfectly for the 2 sliders. I have attached the gif.

**Comment by IbrahimSulai** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33604125/70441376-47db1200-1aba-11ea-8d0d-f14754cf8a07.gif)

**Comment by harishsn** [comment]
@IbrahimSulai Sorry, Had issue with my code initialisation. Fixed it. Thanks.
